import React from 'react';
import { Pressable, type StyleProp, type ViewStyle } from 'react-native';
import {
  type LucideIcon,
  Plus,
  PlusCircle,
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowDown,
  Building2,
  Calendar,
  Car,
  PartyPopper,
  Phone,
  Camera,
  CreditCard,
  Banknote,
  MessageCircle,
  Check,
  CheckCircle2,
  CheckCheck,
  ChevronLeft,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Clipboard,
  X,
  XCircle,
  UploadCloud,
  Wrench,
  Copy,
  SquarePen,
  FileText,
  Download,
  Circle,
  CircleDot,
  MoreVertical,
  Eye,
  EyeOff,
  Inbox,
  LayoutGrid,
  Smile,
  Heart,
  HelpCircle,
  Home,
  Hourglass,
  Image as ImageIcon,
  Info,
  Lock,
  LogOut,
  Mail,
  Megaphone,
  Bell,
  Users,
  User,
  UserPlus,
  Smartphone,
  Store,
  QrCode,
  Receipt,
  RefreshCw,
  MinusCircle,
  Search,
  Shield,
  Sparkles,
  Clock,
  Wallet,
} from 'lucide-react-native';

// Peta nama ikon gaya-Ionicons (dipakai di seluruh app) -> komponen Lucide.
// Ganti tampilan ke gaya garis-tipis Lucide tanpa mengubah nama di call-site.
const ICONS: Record<string, LucideIcon> = {
  add: Plus,
  'add-circle-outline': PlusCircle,
  'alert-circle': AlertCircle,
  'alert-circle-outline': AlertCircle,
  'arrow-back': ArrowLeft,
  'arrow-down-outline': ArrowDown,
  business: Building2,
  calendar: Calendar,
  'calendar-outline': Calendar,
  car: Car,
  'car-outline': Car,
  party: PartyPopper,
  'party-outline': PartyPopper,
  call: Phone,
  camera: Camera,
  card: CreditCard,
  'card-outline': CreditCard,
  cash: Banknote,
  'cash-outline': Banknote,
  'chatbox-ellipses-outline': MessageCircle,
  'chatbubble-ellipses': MessageCircle,
  checkmark: Check,
  'checkmark-circle': CheckCircle2,
  'checkmark-circle-outline': CheckCircle2,
  'checkmark-done': CheckCheck,
  'chevron-back': ChevronLeft,
  'chevron-down': ChevronDown,
  'chevron-forward': ChevronRight,
  'chevron-up': ChevronUp,
  'clipboard-outline': Clipboard,
  'close-circle-outline': XCircle,
  'close': X,
  'cloud-upload-outline': UploadCloud,
  'construct-outline': Wrench,
  'copy-outline': Copy,
  create: SquarePen,
  'create-outline': SquarePen,
  'document-text': FileText,
  'document-text-outline': FileText,
  'download-outline': Download,
  ellipse: Circle,
  'ellipsis-vertical': MoreVertical,
  eye: Eye,
  'eye-outline': Eye,
  'eye-off-outline': EyeOff,
  'file-tray-outline': Inbox,
  'grid-outline': LayoutGrid,
  'happy-outline': Smile,
  heart: Heart,
  'heart-outline': Heart,
  'help-circle': HelpCircle,
  'help-circle-outline': HelpCircle,
  home: Home,
  'home-outline': Home,
  'hourglass-outline': Hourglass,
  image: ImageIcon,
  'image-outline': ImageIcon,
  'information-circle': Info,
  'information-circle-outline': Info,
  'lock-closed-outline': Lock,
  'log-out-outline': LogOut,
  'logo-whatsapp': MessageCircle,
  mail: Mail,
  'mail-outline': Mail,
  megaphone: Megaphone,
  'megaphone-outline': Megaphone,
  notifications: Bell,
  'notifications-outline': Bell,
  people: Users,
  'people-outline': Users,
  'people-circle': Users,
  'people-circle-outline': Users,
  person: User,
  'person-outline': User,
  'person-add-outline': UserPlus,
  'phone-portrait-outline': Smartphone,
  'qr-code': QrCode,
  'radio-button-off': Circle,
  'radio-button-on': CircleDot,
  receipt: Receipt,
  'receipt-outline': Receipt,
  refresh: RefreshCw,
  'remove-circle-outline': MinusCircle,
  search: Search,
  shield: Shield,
  'shield-outline': Shield,
  storefront: Store,
  'storefront-outline': Store,
  'sparkles-outline': Sparkles,
  time: Clock,
  'time-outline': Clock,
  wallet: Wallet,
  'wallet-outline': Wallet,
  warning: AlertTriangle,
  'warning-outline': AlertTriangle,
};

export type IconName = string;

type IconProps = {
  name: string;
  size?: number;
  color?: string;
  style?: StyleProp<ViewStyle>;
  strokeWidth?: number;
  onPress?: () => void;
};

/** Pengganti drop-in untuk <Ionicons/>, dirender dengan ikon Lucide. */
export function Icon({ name, size = 24, color = '#000', style, strokeWidth = 2, onPress }: IconProps) {
  const Cmp = ICONS[name] ?? Circle;
  const glyph = <Cmp size={size} color={color} strokeWidth={strokeWidth} style={onPress ? undefined : style} />;
  if (onPress) {
    return (
      <Pressable onPress={onPress} hitSlop={8} style={style}>
        {glyph}
      </Pressable>
    );
  }
  return glyph;
}
